"""Initial migration

Revision ID: 001
Revises: 
Create Date: 2025-01-08 00:35:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create users table
    op.create_table('users',
        sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('gen_random_uuid()'), nullable=False),
        sa.Column('username', sa.String(), nullable=False),
        sa.Column('password', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('username')
    )
    
    # Create objects table
    op.create_table('objects',
        sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('gen_random_uuid()'), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('description', sa.Text(), nullable=False),
        sa.Column('type', sa.String(), nullable=False),
        sa.Column('attributes', postgresql.JSONB(), server_default='{}', nullable=True),
        sa.Column('tables', postgresql.JSONB(), server_default='[]', nullable=True),
        sa.Column('created_date', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
        sa.Column('modified_date', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
        sa.Column('revision', sa.Integer(), server_default='1', nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    
    # Create relations table
    op.create_table('relations',
        sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('gen_random_uuid()'), nullable=False),
        sa.Column('primary_object_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('secondary_object_ids', postgresql.JSONB(), server_default='[]', nullable=True),
        sa.Column('relation_type', sa.String(), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    
    # Create hierarchies table
    op.create_table('hierarchies',
        sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('gen_random_uuid()'), nullable=False),
        sa.Column('parent_object_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('child_object_ids', postgresql.JSONB(), server_default='[]', nullable=True),
        sa.Column('level', sa.Integer(), server_default='0', nullable=True),
        sa.Column('properties', postgresql.JSONB(), server_default='{}', nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    
    # Create chat_sessions table
    op.create_table('chat_sessions',
        sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('gen_random_uuid()'), nullable=False),
        sa.Column('messages', postgresql.JSONB(), server_default='[]', nullable=True),
        sa.Column('created_date', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.drop_table('chat_sessions')
    op.drop_table('hierarchies')
    op.drop_table('relations')
    op.drop_table('objects')
    op.drop_table('users')
    
    # ### end Alembic commands ###
