"""Add new table

Revision ID: bf23d2df9e27
Revises: 001
Create Date: 2025-09-09 23:49:46.570262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf23d2df9e27'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('messages', sa.JSON(), nullable=True),
    sa.Column('created_date', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hierarchies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('parent_object_id', sa.UUID(), nullable=True),
    sa.Column('child_object_ids', sa.JSON(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('properties', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('relations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('primary_object_id', sa.UUID(), nullable=False),
    sa.Column('secondary_object_ids', sa.JSON(), nullable=True),
    sa.Column('relation_type', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.alter_column('objects', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('objects', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('objects', 'type',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('objects', 'type',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('objects', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('objects', 'name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_table('users')
    op.drop_table('relations')
    op.drop_table('hierarchies')
    op.drop_table('chat_sessions')
    # ### end Alembic commands ###
